//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditApprover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalRequest
    {
        public int ApprovalRequestId { get; set; }
        public Nullable<int> CreditRequestId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
