//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditApprover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRequest
    {
        public int CreditRequestId { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> ApplicantId { get; set; }
    }
}
